(cl:defpackage stretchsense-msg
  (:use )
  (:export
   "<SMARTGLOVESERVERACTION>"
   "SMARTGLOVESERVERACTION"
   "<SMARTGLOVESERVERACTIONFEEDBACK>"
   "SMARTGLOVESERVERACTIONFEEDBACK"
   "<SMARTGLOVESERVERACTIONGOAL>"
   "SMARTGLOVESERVERACTIONGOAL"
   "<SMARTGLOVESERVERACTIONRESULT>"
   "SMARTGLOVESERVERACTIONRESULT"
   "<SMARTGLOVESERVERFEEDBACK>"
   "SMARTGLOVESERVERFEEDBACK"
   "<SMARTGLOVESERVERGOAL>"
   "SMARTGLOVESERVERGOAL"
   "<SMARTGLOVESERVERRESULT>"
   "SMARTGLOVESERVERRESULT"
  ))

