; Auto-generated. Do not edit!


(cl:in-package stretchsense-msg)


;//! \htmlinclude smartGloveServerFeedback.msg.html

(cl:defclass <smartGloveServerFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type cl:string
    :initform ""))
)

(cl:defclass smartGloveServerFeedback (<smartGloveServerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <smartGloveServerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'smartGloveServerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name stretchsense-msg:<smartGloveServerFeedback> is deprecated: use stretchsense-msg:smartGloveServerFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <smartGloveServerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader stretchsense-msg:feedback-val is deprecated.  Use stretchsense-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <smartGloveServerFeedback>) ostream)
  "Serializes a message object of type '<smartGloveServerFeedback>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'feedback))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'feedback))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <smartGloveServerFeedback>) istream)
  "Deserializes a message object of type '<smartGloveServerFeedback>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'feedback) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'feedback) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<smartGloveServerFeedback>)))
  "Returns string type for a message object of type '<smartGloveServerFeedback>"
  "stretchsense/smartGloveServerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'smartGloveServerFeedback)))
  "Returns string type for a message object of type 'smartGloveServerFeedback"
  "stretchsense/smartGloveServerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<smartGloveServerFeedback>)))
  "Returns md5sum for a message object of type '<smartGloveServerFeedback>"
  "c14cdf907e5c7c7fd47292add15660f0")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'smartGloveServerFeedback)))
  "Returns md5sum for a message object of type 'smartGloveServerFeedback"
  "c14cdf907e5c7c7fd47292add15660f0")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<smartGloveServerFeedback>)))
  "Returns full string definition for message of type '<smartGloveServerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%string feedback  # used to show scanning~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'smartGloveServerFeedback)))
  "Returns full string definition for message of type 'smartGloveServerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%string feedback  # used to show scanning~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <smartGloveServerFeedback>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <smartGloveServerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'smartGloveServerFeedback
    (cl:cons ':feedback (feedback msg))
))
