; Auto-generated. Do not edit!


(cl:in-package stretchsense-msg)


;//! \htmlinclude smartGloveServerResult.msg.html

(cl:defclass <smartGloveServerResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element "")))
)

(cl:defclass smartGloveServerResult (<smartGloveServerResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <smartGloveServerResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'smartGloveServerResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name stretchsense-msg:<smartGloveServerResult> is deprecated: use stretchsense-msg:smartGloveServerResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <smartGloveServerResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader stretchsense-msg:result-val is deprecated.  Use stretchsense-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <smartGloveServerResult>) ostream)
  "Serializes a message object of type '<smartGloveServerResult>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'result))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'result))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <smartGloveServerResult>) istream)
  "Deserializes a message object of type '<smartGloveServerResult>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'result) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'result)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<smartGloveServerResult>)))
  "Returns string type for a message object of type '<smartGloveServerResult>"
  "stretchsense/smartGloveServerResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'smartGloveServerResult)))
  "Returns string type for a message object of type 'smartGloveServerResult"
  "stretchsense/smartGloveServerResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<smartGloveServerResult>)))
  "Returns md5sum for a message object of type '<smartGloveServerResult>"
  "d671534a9998964137887d0b28abf896")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'smartGloveServerResult)))
  "Returns md5sum for a message object of type 'smartGloveServerResult"
  "d671534a9998964137887d0b28abf896")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<smartGloveServerResult>)))
  "Returns full string definition for message of type '<smartGloveServerResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%string[] result  # list of devices or true if connected~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'smartGloveServerResult)))
  "Returns full string definition for message of type 'smartGloveServerResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%string[] result  # list of devices or true if connected~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <smartGloveServerResult>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'result) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <smartGloveServerResult>))
  "Converts a ROS message object to a list"
  (cl:list 'smartGloveServerResult
    (cl:cons ':result (result msg))
))
