; Auto-generated. Do not edit!


(cl:in-package stretchsense-msg)


;//! \htmlinclude smartGloveServerGoal.msg.html

(cl:defclass <smartGloveServerGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type (cl:vector cl:string)
   :initform (cl:make-array 0 :element-type 'cl:string :initial-element "")))
)

(cl:defclass smartGloveServerGoal (<smartGloveServerGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <smartGloveServerGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'smartGloveServerGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name stretchsense-msg:<smartGloveServerGoal> is deprecated: use stretchsense-msg:smartGloveServerGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <smartGloveServerGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader stretchsense-msg:goal-val is deprecated.  Use stretchsense-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <smartGloveServerGoal>) ostream)
  "Serializes a message object of type '<smartGloveServerGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'goal))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((__ros_str_len (cl:length ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) ele))
   (cl:slot-value msg 'goal))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <smartGloveServerGoal>) istream)
  "Deserializes a message object of type '<smartGloveServerGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'goal) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'goal)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:aref vals i) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:aref vals i) __ros_str_idx) (cl:code-char (cl:read-byte istream))))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<smartGloveServerGoal>)))
  "Returns string type for a message object of type '<smartGloveServerGoal>"
  "stretchsense/smartGloveServerGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'smartGloveServerGoal)))
  "Returns string type for a message object of type 'smartGloveServerGoal"
  "stretchsense/smartGloveServerGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<smartGloveServerGoal>)))
  "Returns md5sum for a message object of type '<smartGloveServerGoal>"
  "a81c39d59dcc333ed1c4342120568807")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'smartGloveServerGoal)))
  "Returns md5sum for a message object of type 'smartGloveServerGoal"
  "a81c39d59dcc333ed1c4342120568807")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<smartGloveServerGoal>)))
  "Returns full string definition for message of type '<smartGloveServerGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string[] goal  # Specify what the goal is~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'smartGloveServerGoal)))
  "Returns full string definition for message of type 'smartGloveServerGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string[] goal  # Specify what the goal is~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <smartGloveServerGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'goal) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4 (cl:length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <smartGloveServerGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'smartGloveServerGoal
    (cl:cons ':goal (goal msg))
))
