// Generated by gencpp from file stretchsense/smartGloveServerResult.msg
// DO NOT EDIT!


#ifndef STRETCHSENSE_MESSAGE_SMARTGLOVESERVERRESULT_H
#define STRETCHSENSE_MESSAGE_SMARTGLOVESERVERRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stretchsense
{
template <class ContainerAllocator>
struct smartGloveServerResult_
{
  typedef smartGloveServerResult_<ContainerAllocator> Type;

  smartGloveServerResult_()
    : result()  {
    }
  smartGloveServerResult_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::stretchsense::smartGloveServerResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stretchsense::smartGloveServerResult_<ContainerAllocator> const> ConstPtr;

}; // struct smartGloveServerResult_

typedef ::stretchsense::smartGloveServerResult_<std::allocator<void> > smartGloveServerResult;

typedef boost::shared_ptr< ::stretchsense::smartGloveServerResult > smartGloveServerResultPtr;
typedef boost::shared_ptr< ::stretchsense::smartGloveServerResult const> smartGloveServerResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stretchsense::smartGloveServerResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stretchsense::smartGloveServerResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stretchsense::smartGloveServerResult_<ContainerAllocator1> & lhs, const ::stretchsense::smartGloveServerResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stretchsense::smartGloveServerResult_<ContainerAllocator1> & lhs, const ::stretchsense::smartGloveServerResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stretchsense

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stretchsense::smartGloveServerResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stretchsense::smartGloveServerResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stretchsense::smartGloveServerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stretchsense::smartGloveServerResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stretchsense::smartGloveServerResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stretchsense::smartGloveServerResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stretchsense::smartGloveServerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d671534a9998964137887d0b28abf896";
  }

  static const char* value(const ::stretchsense::smartGloveServerResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd671534a99989641ULL;
  static const uint64_t static_value2 = 0x37887d0b28abf896ULL;
};

template<class ContainerAllocator>
struct DataType< ::stretchsense::smartGloveServerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stretchsense/smartGloveServerResult";
  }

  static const char* value(const ::stretchsense::smartGloveServerResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stretchsense::smartGloveServerResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the result\n"
"string[] result  # list of devices or true if connected\n"
;
  }

  static const char* value(const ::stretchsense::smartGloveServerResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stretchsense::smartGloveServerResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct smartGloveServerResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stretchsense::smartGloveServerResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stretchsense::smartGloveServerResult_<ContainerAllocator>& v)
  {
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STRETCHSENSE_MESSAGE_SMARTGLOVESERVERRESULT_H
